# Speak module
GTTS_ENGINE = "gtts"
GTTS_AUDIO_FILENAME = "textaudio.mp3"
GTTS_TLD = "com"
GTTS_LANG = "en"
PYTTSX3_ENGINE = "pyttsx3"
PYTTSX3_RATE = 162
PYTTSX3_VOLUME = 0.8
PYTTSX3_VOICE_INDEX = 0.8
SPEECH_ENGINE_DEFAULT = GTTS_ENGINE


# Hear module
DURATION_AMBIENT_NOISE_ADJUSTMENT = 2
